services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:${HTTP_PORT}"
    restart: always

volumes:
  postgres_data:

